### ISSUE TITLE
Error when requiring util

### ISSUE THREAD

**Issue by CMCDragonkai** [balena-io-modules/ometa-js#11]
If I write this `var util = require('util');` anywhere in a JS file for OMeta to convert, it results in a `SyntaxError: match failed`. If I remove it, it can convert it. Not sure why this is happening.

**Comment by Page-** [comment]
Hey, I just tried compiling

```
var util = require('util');
ometa Test {}
```

using ometajs2js and (correctly) got the following output

```
!function(root, factory) {
    "function" == typeof define && define.amd ? define([ "require", "exports", "ometa-core", "util" ], factory) : "object" == typeof exports ? factory(require, exports, require("ometa-js").core) : factory(function(moduleName) {
        return root[moduleName];
    }, root, root.OMeta);
}(this, function(require, exports, OMeta) {
    var util = require("util"), Test = OMeta._extend({});
});
```

Can you post a full example that fails for me to look into?

**Comment by CMCDragonkai** [comment]
That's the weirdest thing. I put it in today, and it all works now. (Tried it multiple times yesterday) Must have been heisenbug.
